import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")["light"],
          "primary": "#FFFFFF",
          "primary-content": "#000000",
          "secondary": "#F2F2F2",
          "secondary-content": "#E5E6E6",
          "accent": "#2B3440",
          "accent-content": "#e1e5ea",
          "neutral": "#e6e6e6",
          "neutral-content": "#d9d9d9",
          "base-100": "#F2F2F2",
          "base-200": "#e0ebeb",
          "base-300": "#e6e6e6",
          "base-content": "#e0e5eb",
        },
        dark: {
          ...require("daisyui/src/theming/themes")["dark"],
          "primary": "#15191e",
          "primary-content": "#FFFFFF",
          "secondary": "#191E24",
          "secondary-content": "#15191E",
          "accent": "#14191f",
          "accent-content": "#A6ADBB",
          "neutral": "#333333",
          "neutral-content": "#FFFFFF",
          "base-100": "#2a323c",
          "base-200": "#141f1f",
          "base-300": "#262626",
          "base-content": "#14191f",

        },
        acid: {
          ...require("daisyui/src/theming/themes")["acid"],
          "primary": "#97b59c",
          "primary-content": "#000000",
          "secondary": "#ccd8c0",
          "secondary-content": "#e3eedd",
          "accent": "#b0bca9",
          "accent-content": "#C1D0B5",
          "neutral": "#c3d6c2",
          "neutral-content": "#d9d9d9",
          "base-100": "#d2e3c8",
          "base-200": "#e0ebeb",
          "base-300": "#e6e6e6",
          "base-content": "#b3c5a0",
        },
        night: {
          ...require("daisyui/src/theming/themes")["night"],
          "primary": "#0b1109",
          "primary-content": "#FFFFFF",
          "secondary": "#1a1f14",
          "secondary-content": "#172211",
          "accent": "#3e4837",
          "accent-content": "#323e28",
          "neutral": "#151f14",
          "neutral-content": "#FFFFFF",
          "base-100": "#172211",
          "base-200": "#141f1f",
          "base-300": "#262626",
          "base-content": "#333f27",
        },

        halloween: {
          ...require("daisyui/src/theming/themes")["halloween"],
          "primary": "#f8f5d3",
          "primary-content": "#000000",
          "secondary": "#ffffe6",
          "secondary-content": "#ffeecc",
          "accent": "#fcfae9",
          "accent-content": "#FFFFE6",
          "neutral": "#c3d6c2",
          "neutral-content": "#fcfae9",
          "base-100": "#fcfae9",
          "base-200": "#e0ebeb",
          "base-300": "#e6e6e6",
          "base-content": "#f9f5d2",
        },
        lemonade: {
          ...require("daisyui/src/theming/themes")["lemonade"],
          "primary": "#2c2907",
          "primary-content": "#FFFFFF",
          "secondary": "#1A1A00",
          "secondary-content": "#6e6711",
          "accent": "#333300",
          "accent-content": "#1a1a00",
          "neutral": "#151f14",
          "neutral-content": "#847b15",
          "base-100": "#59520d",
          "base-200": "#141f1f",
          "base-300": "#262626",
          "base-content": "#161503",
        },

        emerald: {
          ...require("daisyui/src/theming/themes")["halloween"],
          "primary": "#a8ba78",
          "primary-content": "#000000",
          "secondary": "#eef7d4",
          "secondary-content": "#dee5cd",
          "accent": "#c6cbb3",
          "accent-content": "#d5ea95",
          "neutral": "#c3d6c2",
          "neutral-content": "#fcfae9",
          "base-100": "#fcfae9",
          "base-200": "#e0ebeb",
          "base-300": "#e6e6e6",
          "base-content": "#f9f5d2",
        },
        corporate: {
          ...require("daisyui/src/theming/themes")["lemonade"],
          "primary": "#1d2211",
          "primary-content": "#FFFFFF",
          "secondary": "#222b08",
          "secondary-content": "#3b4323",
          "accent": "#1c1e15",
          "accent-content": "#1a1a00",
          "neutral": "#151f14",
          "neutral-content": "#847b15",
          "base-100": "#59520d",
          "base-200": "#141f1f",
          "base-300": "#262626",
          "base-content": "#161503",
        },
        

        cyberpunk: {
          ...require("daisyui/src/theming/themes")["cyberpunk"],
          "primary": "#A0C49D",
          "primary-content": "#000000",
          "secondary": "#C4D7B2",
          "secondary-content": "#E1ECC8",
          "accent": "#F7FFE5",
          "accent-content": "#e5eedd",
          "neutral": "#c3d6c2",
          "neutral-content": "#fcfae9",
          "base-100": "#fcfae9",
          "base-200": "#e0ebeb",
          "base-300": "#e6e6e6",
          "base-content": "#84b380",
        },
        valentine: {
          ...require("daisyui/src/theming/themes")["valentine"],
          "primary": "#1e301d",
          "primary-content": "#FFFFFF",
          "secondary": "#192211",
          "secondary-content": "#2e3914",
          "accent": "#243300",
          "accent-content": "#324422",
          "neutral": "#151f14",
          "neutral-content": "#847b15",
          "base-100": "#2d2906",
          "base-200": "#141f1f",
          "base-300": "#262626",
          "base-content": "#142013",
        },
        

      },

    ],
  },
  plugins: [require("daisyui")],
}
export default config
